version: "3.8"

services:
  kidney-app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./artifacts:/app/artifacts
      - ./model:/app/model
      - ./config:/app/config

    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    ports:
      - "3000:3000"
    
    environment:
      - NODE_ENV=production
    
    restart: unless-stopped
    
    depends_on:
      - kidney-app